/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string, 'slug' : string }
export interface Channel {
  'id' : bigint,
  'order' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'logoUrl' : string,
  'category' : string,
  'streamUrl' : string,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[Category, string], undefined>,
  'addChannel' : ActorMethod<[Channel, string], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'adminLogout' : ActorMethod<[string], boolean>,
  'deleteCategory' : ActorMethod<[bigint, string], undefined>,
  'deleteChannel' : ActorMethod<[bigint, string], undefined>,
  'getAllChannels' : ActorMethod<[string], Array<Channel>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getChannelById' : ActorMethod<[bigint], Channel>,
  'getChannels' : ActorMethod<[], Array<Channel>>,
  'getChannelsByCategory' : ActorMethod<[string], Array<Channel>>,
  'updateCategory' : ActorMethod<[Category, string], undefined>,
  'updateChannel' : ActorMethod<[Channel, string], undefined>,
  'validateSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];