/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
});
export const Channel = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'logoUrl' : IDL.Text,
  'category' : IDL.Text,
  'streamUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([Category, IDL.Text], [], []),
  'addChannel' : IDL.Func([Channel, IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteChannel' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllChannels' : IDL.Func([IDL.Text], [IDL.Vec(Channel)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getChannelById' : IDL.Func([IDL.Nat], [Channel], ['query']),
  'getChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getChannelsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Channel)], ['query']),
  'updateCategory' : IDL.Func([Category, IDL.Text], [], []),
  'updateChannel' : IDL.Func([Channel, IDL.Text], [], []),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
  });
  const Channel = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'logoUrl' : IDL.Text,
    'category' : IDL.Text,
    'streamUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([Category, IDL.Text], [], []),
    'addChannel' : IDL.Func([Channel, IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteChannel' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllChannels' : IDL.Func([IDL.Text], [IDL.Vec(Channel)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getChannelById' : IDL.Func([IDL.Nat], [Channel], ['query']),
    'getChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getChannelsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Channel)],
        ['query'],
      ),
    'updateCategory' : IDL.Func([Category, IDL.Text], [], []),
    'updateChannel' : IDL.Func([Channel, IDL.Text], [], []),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };